config/routes.rb
Rails.application.routes.draw do
  resources :requests

  resources :books
  devise_for :users
  root "home#index"
  
  get "home/index"
  
  get 'users/profile', as: 'user_root'
  get 'users/profile'

  get 'users/books' 
  get 'users/groups'

end

app/models/book.rb
class Book < ActiveRecord::Base

 belongs_to :user

end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password,:city) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :city, :email, :password, :current_password, :is_female, :date_of_birth) }
    end

    def cities
    	f = File.readlines("/public/cities.dat")
    	@cities = []
    	f.each { |e| cities<<e.strip  }
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to users_books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to users_books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :description, :author, :user_id )

    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

	def index
		city = current_user.city
		users_in_city = User.where(:city => current_user.city).where.not(:id => current_user.id)
		@shelf = []
		users_in_city.each do |u|
			@shelf += Book.where(:user_id => u.id)
		end
	end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /requestys
  # GET /requests.json
  def index
    own_id = current_user.id
    @all_requests = Request.all
    @requests_to_me = Request.where(:requested => own_id).where.not(:accepted => "deleted")
    @my_requests = Request.where(:requester => own_id)
  end

  # GET /requests/new
  def new
    requester = params['requester'].to_i
    requested_book = params['requested_book'].to_i
    requested = params['requested'].to_i
    accepted = "waiting"

    @request = Request.new(:requester => requester, :requested_book => requested_book,
                           :requested => requested, :accepted => accepted)
    @request.save

    redirect_to requests_path
  end

  # since we're in hurry(and we won't need these methods later) let's assume that 
  # show - will mean accepting request by user and edit - rejecting
  # GET /requests/1/edit
  def edit
    # @request = Request.find_by(params[:id])
    # determine other book in return
    @request.accepted = "rejected"
    @request.save

    redirect_to requests_path
  end

  # GET /requests/1
  # GET /requests/1.json
  # def show
  #   # @request = Request.find_by(params[:id])
  #   @request.accepted = "accepted"

  #   @request.save

  #   redirect_to requests_path
  # end

  def show
  end

  def update
    @request.requester_book = params[:requester_book]
    @request.accepted = "accepted"

    @request.save

    redirect_to requests_path
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    # @request = Request.find_by(params[:id])
    @request.accepted = "deleted"
    @request.save

    redirect_to requests_path

    # @request.destroy
    # respond_to do |format|
    #   format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:requester, :requested_book, :requested, :requester_book, :accepted)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def profile
  end

  def books
  	@books = current_user.books
  end

  def groups
  	@close_users = User.where(:city => current_user.city).where.not(:id => current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>
<p>
  <strong>Owner:</strong>
  <%= User.find_by(id: @book.user_id).name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<ul class="collection with-header">
    <li class="collection-header"><h4><b>Currently on the <i>shelf: </i></b></h3></li>
    <% @shelf.each do |book| %>
        <li class="collection-item"><div><h4><b><%= book.title %></b>, <%= book.author %></h4><%= link_to "want it!", new_request_path(:requester => current_user.id, :requested_book => book.id,
                                 :requested => book.user_id) %></div></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book swapping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="materialize.min.js"></script>
  <%= stylesheet_link_tag "icons" %>  
</head>
<body>
<% if user_signed_in? %>
<%
@quantity = Request.where(:requested => current_user.id, :accepted => 'waiting')
%>
<% end -%>

<div>
    <span class = "btn"><%=link_to  "Home", root_path%></span>
<% if user_signed_in? %>
    <span>Hello, <%= current_user.name %></span>
     <span class = "btn"><%= link_to 'My Books', users_books_path%></span>
     <span class = "btn"><%= link_to 'Trades', requests_path %> 
         <%if @quantity.count > 0 %>
          <%= @quantity.count %>
          <%end%>
     
     </span>
    <span class = "btn" ><%= link_to 'Edit account', edit_user_registration_path %></span>
     <span class = "btn"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %> </span>
<% else %>
    
    
<% end %>

</div>

<%= yield %>

</body>
</html>

app/views/requests/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Requests to Me</h1>

<script type="text/javascript">
  var a = 5;

</script>

<table>
  <thead>
    <tr>
      <th>Requester</th>
      <th>Requested book</th>
      <th>Requester book</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests_to_me.each do |request| %>
      <tr>
        <td><%= User.find(request.requester).name %></td>
        <td><b><%= Book.find(request.requested_book).title %></b>, <%= Book.find(request.requested_book).author %> </td>
        <td>
        <%@r_books = Book.where(user_id: request.requester) %>
        <%@r_books_titles = []%>
        <% @r_books.each  { |book| @r_books_titles<<[book.title,book.id]}%>
        
        <% if request.accepted == "waiting" %>
          <%= form_for(request) do |f| %>
          <%= select_tag(:requester_book, options_for_select(@r_books_titles))  %>
          <div class="actions">
            <%= f.submit "Accept" %>
          </div>
          <% end %>
        <% end %>

        </td>
        <td><%= request.accepted %></td>


        <td><%= link_to 'Reject', edit_request_path(request) if request.accepted == "waiting" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h1>Listing Requests from Me</h1>

<table>
  <thead>
    <tr>
      <th>Requested book</th>
      <th>Requested</th>
      <th>Requester book</th>
      <th>Status</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_requests.each do |request| %>
      <tr>
        <td><b><%= Book.find(request.requested_book).title %></b>, <%= Book.find(request.requested_book).author %></td>
        <td><%= User.find(request.requested).name %></td>
        <td><%= Book.find(request.requester_book) if request.requester_book %></td>
        <td><%= request.accepted %></td>
        <td><%= link_to 'Cancel', request, method: :delete, data: { confirm: 'Are you sure?' } if request.accepted == "waiting" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/users/books.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.author %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/users/groups.html.erb
There should be list of all users available to trade
<br>

<ul class="collection">
<% @close_users.each do |user| %>
	<li class="collection-item"><%= user.email %></li>
<% end %>
</ul>

app/views/users/profile.html.erb
My info:<br>
My name<br>
<%=current_user.name %><br>
ID = <%= current_user.id %> <br><br>
City = <%=current_user.city%>
My list of books:<br>
<%= link_to "test", users_books_path %>
<%= link_to "Group", users_groups_path %>